# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI (linters, unit testing, pushing Docker image)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_and_validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Build and install package
      run: |
        poetry build
        pip install dist/$(ls dist | grep .*.whl)
    - name: Run ruff
      run: poetry run ruff check . -v
    - name: Run black (dry run)
      run: poetry run black --check . -v
    - name: Run unit tests
      run: pytest
  
  push_to_docker_repo:
    needs: build_and_validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6  
        with:
          image: arazi99/ws2g
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
