# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: WS2G push & PR unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install poetry
      run: |
        pip install poetry
    - name: Build and install package
      run: |
        poetry build
        pip install dist/$(ls dist | grep .*.whl)
    - name: Install pytest
      run: pip install pytest
    - name: Install pytest-cov
      run: pip install pytest-cov
    - name: pip show ws2g
      run: pip show ws2g
    - name: which pip
      run: which pip
    - name: which pytest
      run: which pytest
    - name: which python
      run: which python
    - name: cd tests
      run: cd tests
    - name: echo pythonpath
      run: echo $PYTHONPATH
    - name: Run unit tests 3
      if: always()
      # https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#invoking-pytest-versus-python-m-pytest
      run: pytest
    - name: Run unit tests x
      if: always()
      # https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#invoking-pytest-versus-python-m-pytest
      run: python -m pytest tests
    - name: Run unit tests 4
      if: always()
      # https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#invoking-pytest-versus-python-m-pytest
      run: python -m pytest
    - name: Run unit tests 7
      if: always()
      # https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#invoking-pytest-versus-python-m-pytest
      run: pytest tests
    - name: Run unit tests 8
      if: always()
      # https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#invoking-pytest-versus-python-m-pytest
      run: python -m pytest tests
